CREATE TABLE IF NOT EXISTS rankings_ia (
  vacante_id INT PRIMARY KEY,
  ranking MEDIUMTEXT NOT NULL,
  ranking_hash VARCHAR(64) NOT NULL,
  generado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (vacante_id) REFERENCES vacantes(id) ON DELETE CASCADE
);
